version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  apache:
    image: php:8.1-apache
    container_name: apache
    ports:
      - 8000:80
    volumes:
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./backend:/var/www
    command: bash -c "a2enmod rewrite && apache2-foreground"
